In [7]:
import pandas as pd

file_path = "Irregular Verbs.csv"

df = pd.read_csv(file_path)

In [8]:
df

      Present  Past simple Past participle
0        awake       awoke          awoken
1           be    was/were            been
2         bear        bore            born
3         beat        beat            beat
4       become      became          become
..         ...         ...             ...
171        win         won             won
172   withhold    withheld        withheld
173  withstand   withstood       withstood
174      wring       wrung           wrung
175      write       wrote         written

[176 rows x 3 columns]